apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application1
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/imranmdimranmd/argocd_proj.git
    targetRevision: HEAD
    path: ./kustomization.yaml
  destination: 
    server: https://kubernetes.default.svc
    namespace: myapp3

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true